server.port=8080
spring.application.name=banco-austro

# Configuración Base de Datos Cuenca
datasources.cuenca.url=jdbc:postgresql://localhost:5432/banco_cuenca
datasources.cuenca.username=banco
datasources.cuenca.password=banco123
datasources.cuenca.driver-class-name=org.postgresql.Driver

# Configuración Base de Datos Quito
datasources.quito.url=jdbc:postgresql://localhost:5433/banco_quito
datasources.quito.username=banco
datasources.quito.password=banco123
datasources.quito.driver-class-name=org.postgresql.Driver

# Configuración Base de Datos Guayaquil
datasources.guayaquil.url=jdbc:postgresql://localhost:5434/banco_guayaquil
datasources.guayaquil.username=banco
datasources.guayaquil.password=banco123
datasources.guayaquil.driver-class-name=org.postgresql.Driver